#ifndef UTIL_256x224_H
#define UTIL_256x224_H

#define UTIL_SCREEN_PIXEL_WIDTH 256
#define UTIL_SCREEN_PIXEL_HEIGHT 224
#define UTIL_SCREEN_PIXEL_HEIGHT_MINUS_ONE 223
#define UTIL_SCREEN_TILE_WIDTH 32
#define UTIL_SCREEN_TILE_HEIGHT 32
#define UTIL_SCREEN_TILE_WIDTH_PLUS_ONE 33
#define UTIL_SCREEN_TILE_HEIGHT_PLUS_ONE 33

#define UTIL_VDP_PLANE_TILE_WIDTH 32
#define UTIL_VDP_PLANE_TILE_WIDTH_MINUS_ONE 31
#define UTIL_VDP_PLANE_TILE_WIDTH_TIMES_TWO 64
#define UTIL_VDP_PLANE_TILE_HEIGHT 32
#define UTIL_VDP_PLANE_TILE_HEIGHT_MINUS_ONE 31

#endif // UTIL_256x224_H
